export * from './navbar/navbar'
export * from './hero/hero'
export * from  './button/button'
export * from './about/about'
export * from './training/training'
export * from './card/card'
export * from './team/team'
export * from './team-card/team-card'