import { IPatientData } from "../../interfaces/patient/patient";

export const dummyData: IPatientData[] = [
  {
    no: '01',
    name: 'Risabh Sahu',
    id: '02344',
    affiliation: 'my Tatva',
    dcb: '22/05/2024',
    days: '23 days',
    gender: 'Male',
    case: 'New',
    category: 'General',
    referredBy: 'Dr. Smith',
    time: '03:20 PM',
    status: 'Queue',
  },
  {
    no: '02',
    name: 'John Doe',
    id: '02345',
    affiliation: 'Clinic ABC',
    dcb: '20/05/2024',
    days: '25 days',
    gender: 'Male',
    case: 'Follow-up',
    category: 'Cardiology',
    referredBy: 'Dr. Adams',
    time: '11:00 AM',
    status: 'In Progress',
  },
  {
    no: '03',
    name: 'Jane Smith',
    id: '02346',
    affiliation: 'HealthPlus',
    dcb: '18/05/2024',
    days: '27 days',
    gender: 'Female',
    case: 'New',
    category: 'Dermatology',
    referredBy: 'Dr. Brown',
    time: '01:30 PM',
    status: 'Completed',
  },
  {
    no: '04',
    name: 'Robert Johnson',
    id: '02347',
    affiliation: 'MediCare',
    dcb: '16/05/2024',
    days: '29 days',
    gender: 'Male',
    case: 'Consultation',
    category: 'Neurology',
    referredBy: 'Dr. Lee',
    time: '02:45 PM',
    status: 'Pending',
  },
  {
    no: '05',
    name: 'Emily Davis',
    id: '02348',
    affiliation: 'LifeCare',
    dcb: '14/05/2024',
    days: '31 days',
    gender: 'Female',
    case: 'Review',
    category: 'Orthopedics',
    referredBy: 'Dr. Green',
    time: '09:00 AM',
    status: 'Queue',
  },
  {
    no: '06',
    name: 'Michael Wilson',
    id: '02349',
    affiliation: 'Wellness Center',
    dcb: '12/05/2024',
    days: '33 days',
    gender: 'Male',
    case: 'New',
    category: 'Pediatrics',
    referredBy: 'Dr. White',
    time: '10:15 AM',
    status: 'In Progress',
  },
  {
    no: '07',
    name: 'Sarah Miller',
    id: '02350',
    affiliation: 'City Hospital',
    dcb: '10/05/2024',
    days: '35 days',
    gender: 'Female',
    case: 'Follow-up',
    category: 'Gastroenterology',
    referredBy: 'Dr. Black',
    time: '12:00 PM',
    status: 'Completed',
  },
  {
    no: '08',
    name: 'Risabh Sahu',
    id: '02344',
    affiliation: 'my Tatva',
    dcb: '22/05/2024',
    days: '23 days',
    gender: 'Male',
    case: 'New',
    category: 'General',
    referredBy: 'Dr. Smith',
    time: '03:20 PM',
    status: 'Queue',
  },
  {
    no: '09',
    name: 'John Doe',
    id: '02345',
    affiliation: 'Clinic ABC',
    dcb: '20/05/2024',
    days: '25 days',
    gender: 'Male',
    case: 'Follow-up',
    category: 'Cardiology',
    referredBy: 'Dr. Adams',
    time: '11:00 AM',
    status: 'In Progress',
  },
  {
    no: '10',
    name: 'Jane Smith',
    id: '02346',
    affiliation: 'HealthPlus',
    dcb: '18/05/2024',
    days: '27 days',
    gender: 'Female',
    case: 'New',
    category: 'Dermatology',
    referredBy: 'Dr. Brown',
    time: '01:30 PM',
    status: 'Completed',
  },
  {
    no: '12',
    name: 'Robert Johnson',
    id: '02347',
    affiliation: 'MediCare',
    dcb: '16/05/2024',
    days: '29 days',
    gender: 'Male',
    case: 'Consultation',
    category: 'Neurology',
    referredBy: 'Dr. Lee',
    time: '02:45 PM',
    status: 'Pending',
  },
];
