import { IPatientData } from "../../interfaces/patient/patient";

export const dummyData: IPatientData[] = [
  {
    no: '01',
    name: 'Risabh Sahu',
    id: '02344',
    affiliation: 'meu Tatva',
    dcb: '22/05/2024',
    days: '23 dias',
    gender: 'Masculino',
    case: 'Novo',
    category: 'Geral',
    referredBy: 'Dr. Smith',
    time: '15:20',
    status: 'Fila',
  },
  {
    no: '02',
    name: 'John Doe',
    id: '02345',
    affiliation: 'Clínica ABC',
    dcb: '20/05/2024',
    days: '25 dias',
    gender: 'Masculino',
    case: 'Consulta',
    category: 'Cardiologia',
    referredBy: 'Dr. Adams',
    time: '11:00',
    status: 'Em Progresso',
  },
  {
    no: '03',
    name: 'Jane Smith',
    id: '02346',
    affiliation: 'HealthPlus',
    dcb: '18/05/2024',
    days: '27 dias',
    gender: 'Feminino',
    case: 'Novo',
    category: 'Dermatologia',
    referredBy: 'Dr. Brown',
    time: '13:30',
    status: 'Concluído',
  },
  {
    no: '04',
    name: 'Robert Johnson',
    id: '02347',
    affiliation: 'MediCare',
    dcb: '16/05/2024',
    days: '29 dias',
    gender: 'Masculino',
    case: 'Consulta',
    category: 'Neurologia',
    referredBy: 'Dr. Lee',
    time: '14:45',
    status: 'Pendente',
  },
  {
    no: '05',
    name: 'Emily Davis',
    id: '02348',
    affiliation: 'LifeCare',
    dcb: '14/05/2024',
    days: '31 dias',
    gender: 'Feminino',
    case: 'Revisão',
    category: 'Ortopedia',
    referredBy: 'Dr. Green',
    time: '09:00',
    status: 'Fila',
  },
  {
    no: '06',
    name: 'Michael Wilson',
    id: '02349',
    affiliation: 'Centro de Bem-Estar',
    dcb: '12/05/2024',
    days: '33 dias',
    gender: 'Masculino',
    case: 'Novo',
    category: 'Pediatria',
    referredBy: 'Dr. White',
    time: '10:15',
    status: 'Em Progresso',
  },
  {
    no: '07',
    name: 'Sarah Miller',
    id: '02350',
    affiliation: 'Hospital da Cidade',
    dcb: '10/05/2024',
    days: '35 dias',
    gender: 'Feminino',
    case: 'Consulta',
    category: 'Gastroenterologia',
    referredBy: 'Dr. Black',
    time: '12:00',
    status: 'Concluído',
  },
  {
    no: '08',
    name: 'Risabh Sahu',
    id: '02344',
    affiliation: 'meu Tatva',
    dcb: '22/05/2024',
    days: '23 dias',
    gender: 'Masculino',
    case: 'Novo',
    category: 'Geral',
    referredBy: 'Dr. Smith',
    time: '15:20',
    status: 'Fila',
  },
  {
    no: '09',
    name: 'John Doe',
    id: '02345',
    affiliation: 'Clínica ABC',
    dcb: '20/05/2024',
    days: '25 dias',
    gender: 'Masculino',
    case: 'Consulta',
    category: 'Cardiologia',
    referredBy: 'Dr. Adams',
    time: '11:00',
    status: 'Em Progresso',
  },
  {
    no: '10',
    name: 'Jane Smith',
    id: '02346',
    affiliation: 'HealthPlus',
    dcb: '18/05/2024',
    days: '27 dias',
    gender: 'Feminino',
    case: 'Novo',
    category: 'Dermatologia',
    referredBy: 'Dr. Brown',
    time: '13:30',
    status: 'Concluído',
  },
  {
    no: '12',
    name: 'Robert Johnson',
    id: '02347',
    affiliation: 'MediCare',
    dcb: '16/05/2024',
    days: '29 dias',
    gender: 'Masculino',
    case: 'Consulta',
    category: 'Neurologia',
    referredBy: 'Dr. Lee',
    time: '14:45',
    status: 'Pendente',
  },
];
